In [1]:
import numpy as np
import numpy.random as npr
data = np.arange(0,9,1)
print(data)
#s = slice(2,7,2)
print(data[2:5])
print(data[2:])
print(data[2:5:2])

[0 1 2 3 4 5 6 7 8]
[2 3 4]
[2 3 4 5 6 7 8]
[2 4]


In [0]:
datum = np.genfromtxt('cancer_data.csv', delimiter=',', dtype=np.string_)
# except header
datum = datum[1:,:]

In [0]:
# Shuffle
npr.shuffle(datum)

X = datum[:, :2]
Y = datum[:, 2]

In [0]:
# Slice
train_x = X[:60]
test_x = X[60:80]
val_x = X[80:]

train_y= Y[:60]
test_Y = Y[60:80]
val_Y = Y[80:]

In [6]:
print(train_x[3])
print(train_x[5])
print(train_x[7])
print(train_x[11])
print(train_x[[3,5,7]])
print(train_x.dtype)
print(test_x.dtype)

[b'2.301829' b'3.2399511']
[b'4.792593' b'2.5709867']
[b'3.5242965' b'3.7352796']
[b'7.649406' b'8.496426']
[[b'2.301829' b'3.2399511']
 [b'4.792593' b'2.5709867']
 [b'3.5242965' b'3.7352796']]
|S10
|S10


In [0]:
# Member 변수 및 함수이용해서  mean, std, min, max 을 구해봅니다.

# cast np.string to np.float32 
# 2가지 방법이 있습니다.
print(np.asarray(train_x, np.float32))
train_x = train_x.astype(np.float32)

# mean, min, max , std
print(train_x.mean())
print(train_x.min())
print(train_x.max())
print(train_x.std())


In [0]:
# test 
# cast string to float
test_x = test_x.astype(np.float32)

# mean, min, max , std
print(test_x.mean())
print(test_x.min())
print(test_x.max())
print(test_x.std())



In [0]:
# cast string to float
val_x = val_x.astype(np.float32)

# mean, min, max , std
print(val_x.mean())
print(val_x.min())
print(val_x.max())
print(val_x.std())

In [0]:
# tumor size, age 별 mean , std, min, max 구하기 
print('\n')
print(train_x[:,0].mean())
print(train_x[:,0].min())
print(train_x[:,0].max())
print(train_x[:,0].std())

print('\n')
print(train_x[:,1].mean())
print(train_x[:,1].min())
print(train_x[:,1].max())
print(train_x[:,1].std())


print('\n')
print(val_x[:,0].mean())
print(val_x[:,0].min())
print(val_x[:,0].max())
print(val_x[:,0].std())

print('\n')
print(val_x[:,1].mean())
print(val_x[:,1].min())
print(val_x[:,1].max())
print(val_x[:,1].std())

print('\n')
print(test_x[:,0].mean())
print(test_x[:,0].min())
print(test_x[:,0].max())
print(test_x[:,0].std())

print('\n')
print(test_x[:,1].mean())
print(test_x[:,1].min())
print(test_x[:,1].max())
print(test_x[:,1].std())


In [0]:
# Searching
indices = np.where(train_x[:,0]>train_x.mean())[0]
print(np.where(train_x[:,0]>train_x.mean()))
print(train_x[indices])
print(train_x.mean())